### ISSUE TITLE
코딩테스트 대비 풀어보면 좋을 문제들

### ISSUE THREAD

**Issue by saechimdaeki** [AlgorithmStudy/SS-Study#30]
https://www.acmicpc.net/problem/7453 합이 0 인 네 정수
https://www.acmicpc.net/problem/11659 구간합구하기4
https://www.acmicpc.net/problem/15961 회전초밥
https://www.acmicpc.net/problem/4358 생태학
https://www.acmicpc.net/problem/14725 개미굴
https://www.acmicpc.net/problem/7662 이중우선순위큐
https://www.acmicpc.net/problem/14719 빗물
https://www.acmicpc.net/problem/2470 두용액
https://www.acmicpc.net/problem/2212 센서
https://www.acmicpc.net/problem/13164 행복 유치원
https://www.acmicpc.net/problem/1744 수 묶기

**Comment by Gayeoon** [comment]
https://www.acmicpc.net/problem/7453 합이 0 인 네 정수
https://www.acmicpc.net/problem/11659 구간합구하기4
https://www.acmicpc.net/problem/15961 회전초밥
https://www.acmicpc.net/problem/4358 생태학
https://www.acmicpc.net/problem/14725 개미굴
*https://www.acmicpc.net/problem/7662 이중우선순위큐*
https://www.acmicpc.net/problem/14719 빗물

**Comment by Gayeoon** [comment]
https://www.acmicpc.net/problem/7453 합이 0 인 네 정수
https://www.acmicpc.net/problem/11659 구간합구하기4
https://www.acmicpc.net/problem/15961 회전초밥
~~https://www.acmicpc.net/problem/4358 생태학~~
https://www.acmicpc.net/problem/14725 개미굴
~~https://www.acmicpc.net/problem/7662 이중우선순위큐~~
https://www.acmicpc.net/problem/14719 빗물

**Comment by saechimdaeki** [comment]
ㅋㅋㅋㅋㅋ 기업코테 난이도 중심.. 저희가 안푼문제 찾아볼게요 ㅎㅎ...

**Comment by saechimdaeki** [comment]
간단한 실버~골드문제들 안푸신거 확인하고 추가했습니다

**Comment by saechimdaeki** [comment]
다푼것으로 확인하여 해당 이슈를 닫습니다
