### ISSUE TITLE
코딩테스트 대비 풀어보면 좋을 문제들 2

### ISSUE THREAD

**Issue by saechimdaeki** [AlgorithmStudy/SS-Study#43]
### 문제 선정의 기준은 코테에 나올 것 같은 유형 && 가연 안 푼 문제 

https://www.acmicpc.net/problem/2696 중앙 값 구하기 
https://www.acmicpc.net/problem/2109 순회 강연
https://www.acmicpc.net/problem/1644 소수의 연속 합 
https://www.acmicpc.net/problem/1967 트리의 지름
https://www.acmicpc.net/problem/20010 악덕영주 혜유
https://www.acmicpc.net/problem/18232 텔레포트 정거장
https://www.acmicpc.net/problem/2151 거울설치
https://www.acmicpc.net/problem/15565 귀여운 라이언
https://www.acmicpc.net/problem/2812 크게 만들기

**Comment by saechimdaeki** [comment]
2월  첫 째주까지는 이 이슈로 업데이트 합니다.

**Comment by Gayeoon** [comment]
https://www.acmicpc.net/problem/2696 중앙 값 구하기
https://www.acmicpc.net/problem/2109 순회 강연
https://www.acmicpc.net/problem/1644 소수의 연속 합
https://www.acmicpc.net/problem/1967 트리의 지름
https://www.acmicpc.net/problem/20010 악덕영주 혜유
https://www.acmicpc.net/problem/18232 텔레포트 정거장
https://www.acmicpc.net/problem/2151 거울설치
~~https://www.acmicpc.net/problem/15565 귀여운 라이언~~
https://www.acmicpc.net/problem/2812 크게 만들기

**Comment by saechimdaeki** [comment]
이번주 서로 바쁜 일정으로 인해 이슈의 제목을 변경합니다.
